# Site settings
## Change the values as needed.
title: The small home that Li Ancheng
email: lianchenglac@163.com
description: "Only the code can be aroused my interest to do the real geek!!"
keywords: "jekyll, github, html, js,vue,node"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
rouge: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  weibo: u/6032496028
  twitter: liancheng
  email: lianchenglac@163.com
  github: liancheng-zcy.github.io
exclude:
  - bower_components
  - README.md
full_name: LiAncheng

##set this to enable disqus commenting
disqus: bitwiser

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
